// Optional browser smoke test: node tests/browser-flow.mjs <playwright entry> <chromium executable>
// Uses a fresh browser context; never touches a user's browser profile.
import { pathToFileURL } from 'node:url'
import { mkdir } from 'node:fs/promises'
import assert from 'node:assert/strict'
const { chromium } = await import(pathToFileURL(process.argv[2]).href)
const browser = await chromium.launch({ executablePath: process.argv[3], headless: true })
const context = await browser.newContext({ viewport: { width: 1366, height: 900 } })
const page = await context.newPage()
const errors = []
page.on('pageerror', e => errors.push(e.message))
await mkdir('dist/qa', { recursive: true })
const shot = async name => {
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: `dist/qa/${name}.png`, fullPage: true })
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Overflow on ${name}`)
  if (name.endsWith('-desktop')) {
    await page.setViewportSize({ width: 390, height: 844 })
    await page.evaluate(() => window.scrollTo(0, 0))
    await page.screenshot({ path: `dist/qa/${name.replace('-desktop', '-mobile')}.png`, fullPage: true })
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Mobile overflow on ${name}`)
    await page.setViewportSize({ width: 1366, height: 900 })
  }
}
try {
  await page.goto('http://127.0.0.1:5173/home')
  await page.waitForURL('**/login')
  await shot('login-desktop')
  await page.getByLabel('Usuario', { exact: true }).fill('ana')
  await page.getByLabel('Contraseña', { exact: true }).fill('demo123')
  await page.getByRole('button', { name: 'Iniciar sesión', exact: true }).click()
  await page.waitForURL('**/home')
  await shot('home-desktop')
  await page.getByRole('button', { name: /Captura inteligente Nueva visita/ }).click()
  await page.getByRole('button', { name: /Hospital Santo Tomás/ }).click()
  await page.getByLabel('Área', { exact: false }).first().selectOption('Radiología')
  await shot('new-desktop')
  await page.getByRole('button', { name: 'Continuar', exact: true }).filter({ visible: true }).click()
  await page.waitForURL('**/capture')
  await page.getByLabel('Texto de la observación').fill('Dos resonadores y un tomógrafo')
  await page.getByRole('button', { name: 'Voz', exact: true }).click()
  assert.equal(await page.getByLabel('Transcripción editable').inputValue(), 'Dos resonadores y un tomógrafo')
  await page.getByLabel('Transcripción editable').fill('Dos resonadores y un tomógrafo de 64 cortes')
  await page.getByRole('button', { name: 'Chat', exact: true }).click()
  await page.reload()
  assert.equal(await page.getByLabel('Texto de la observación').inputValue(), 'Dos resonadores y un tomógrafo de 64 cortes')
  await shot('capture-desktop')
  await page.getByRole('button', { name: 'Analizar observación' }).click()
  await page.waitForURL('**/review')
  await page.getByRole('heading', { name: 'La IA detectó 3 equipos' }).waitFor()
  await page.getByLabel('Marca', { exact: true }).first().fill('Philips')
  await page.reload()
  assert.equal(await page.getByLabel('Marca', { exact: true }).first().inputValue(), 'Philips')
  await shot('review-desktop')
  await page.getByRole('button', { name: 'Confirmar 3 equipos' }).click()
  await page.waitForURL('**/match')
  assert.equal(await page.getByRole('button', { name: 'Confirmar coincidencias' }).isDisabled(), true)
  await page.getByRole('button', { name: 'Es el mismo equipo', exact: true }).first().click()
  assert.equal(await page.getByRole('button', { name: 'Confirmar coincidencias' }).isDisabled(), true)
  await page.getByRole('button', { name: 'Es diferente / nuevo', exact: true }).last().click()
  await page.reload()
  assert.equal(await page.getByRole('button', { name: 'Confirmar coincidencias' }).isEnabled(), true)
  await shot('match-desktop')
  await page.getByRole('button', { name: 'Confirmar coincidencias' }).click()
  await page.waitForURL('**/success')
  await shot('success-desktop')
  await page.getByRole('button', { name: 'Añadir otra observación' }).click()
  await page.waitForURL('**/capture')
  assert.equal(await page.getByLabel('Texto de la observación').inputValue(), '')
  await page.getByLabel('Texto de la observación').fill('Ultrasonido portátil GE LOGIQ')
  await page.getByRole('button', { name: 'Analizar observación' }).click()
  await page.waitForURL('**/review')
  await page.getByRole('button', { name: 'Confirmar 1 equipo' }).click()
  await page.waitForURL('**/match')
  await page.getByRole('button', { name: 'Confirmar coincidencias' }).click()
  await page.waitForURL('**/success')
  await page.getByRole('button', { name: 'Finalizar visita' }).click()
  await page.waitForURL('**/visits')
  await page.getByLabel('Mostrar visitas de ejemplo (datos simulados)').uncheck()
  await page.getByLabel('Buscar hospital o área').fill('No existe este hospital')
  await page.getByRole('heading', { name: 'No encontramos visitas' }).waitFor()
  await page.getByLabel('Buscar hospital o área').fill('')
  await shot('visits-desktop')
  await page.getByRole('button', { name: /Hospital Santo Tomás.*4 equipos.*2 observaciones/ }).click()
  await page.getByText('Ultrasonido GE LOGIQ', { exact: true }).waitFor()
  await shot('detail-desktop')
  await page.setViewportSize({ width: 390, height: 844 })
  await shot('detail-mobile')
  for (const route of ['/home', '/visits', '/visits/new']) {
    await page.goto(`http://127.0.0.1:5173${route}`)
    await shot(`${route.split('/').at(-1)}-mobile`)
  }
  await page.getByRole('button', { name: /Hospital Santo Tomás/ }).click()
  await page.getByRole('button', { name: 'Continuar', exact: true }).filter({ visible: true }).click()
  await page.getByLabel('Texto de la observación').fill('No se identifican equipos')
  await shot('capture-mobile')
  await page.getByRole('button', { name: 'Analizar observación' }).click()
  await page.waitForURL('**/review')
  await page.getByRole('heading', { name: 'La IA detectó 0 equipos' }).waitFor()
  await shot('empty-review-mobile')
  await context.setOffline(true)
  await page.getByText('Sin conexión.', { exact: false }).first().waitFor()
  await shot('offline-mobile')
  assert.deepEqual(errors, [])
  console.log('PASS: guards, two-observation visit, editable drafts, independent decisions, detail, empty extraction, offline, mobile/desktop overflow.')
} finally { await browser.close() }
